# Generated by Django 6.0 on 2026-01-01 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pessoa", "0001_initial"),
        ("trabalho", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipacaoTrabalho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "papel",
                    models.CharField(
                        choices=[
                            ("AUTOR", "Autor"),
                            ("ORIENTADOR", "Orientador"),
                            ("COORIENTADOR", "Coorientador"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ordem_autoria", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participacoes",
                        to="pessoa.pessoa",
                    ),
                ),
                (
                    "trabalho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participacoes",
                        to="trabalho.trabalho",
                    ),
                ),
            ],
        ),
    ]
