# Generated by Django 6.0 on 2025-12-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Arquivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arquivo", models.FileField(upload_to="trabalhos/")),
                ("tipo", models.CharField(max_length=50)),
                ("tamanho", models.PositiveIntegerField()),
                ("checksum", models.CharField(max_length=64)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
