# Generated by Django 6.0 on 2025-12-21 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("arquivo", "0001_initial"),
        ("trabalho", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="arquivo",
            name="trabalho",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arquivos",
                to="trabalho.trabalho",
            ),
        ),
    ]
