# Generated by Django 6.0 on 2025-12-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arquivo", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="arquivo",
            name="nome",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
