# Generated by Django 6.0 on 2025-12-31 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("telefone", models.CharField(blank=True, max_length=11, null=True)),
                (
                    "titulacao_maxima",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GRAD", "Graduação"),
                            ("ESPE", "Especialização"),
                            ("MEST", "Mestrado"),
                            ("DOUT", "Doutorado"),
                            ("POSDOUT", "Pós-Doutorado"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pessoa",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
