# Generated by Django 6.0 on 2026-01-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pessoa", "0002_alter_pessoa_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pessoa",
            name="cpf",
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
