# Generated by Django 6.0 on 2025-12-21 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departamento", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("sigla", models.CharField(max_length=20)),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("graduacao", "Graduação"),
                            ("pos_graduacao", "Pós-Graduação"),
                            ("tecnico", "Técnico"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="departamento.departamento",
                    ),
                ),
            ],
        ),
    ]
