# Generated by Django 6.0 on 2025-12-21 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curso", "0001_initial"),
        ("palavra_chave", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trabalho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=500)),
                ("resumo", models.TextField()),
                ("ano_defesa", models.PositiveIntegerField()),
                ("data_defesa", models.DateField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ART", "Artigo"),
                            ("MON", "Monografia"),
                            ("DIS", "Dissertação"),
                            ("TES", "Tese"),
                        ],
                        max_length=3,
                    ),
                ),
                ("idioma", models.CharField(max_length=50)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="curso.curso"
                    ),
                ),
                (
                    "palavras_chave",
                    models.ManyToManyField(to="palavra_chave.palavrachave"),
                ),
            ],
        ),
    ]
