# Generated by Django 6.0 on 2026-01-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trabalho", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trabalho",
            name="abstract",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trabalho",
            name="editor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="trabalho",
            name="resumo",
            field=models.TextField(blank=True, null=True),
        ),
    ]
