# Generated by Django 6.0 on 2026-01-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "trabalho",
            "0002_remove_trabalho_autores_remove_trabalho_coorientador_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="trabalho",
            name="disponivel_consulta",
            field=models.BooleanField(default=True),
        ),
    ]
