# Generated by Django 6.0 on 2025-12-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("descricao", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
