# Generated by Django 6.0 on 2025-12-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departamento", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="departamento",
            name="sigla",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="departamento",
            name="codigo",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
